name: CI/CD Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/artinfo-server
  VERSION: ${{ github.sha }}
  CONTANIER_NAME1: artinfo-server-deploy1
  CONTANIER_NAME2: artinfo-server-deploy2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Create Enviroment File
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.application }}" >> ./src/main/resources/application.yml

          touch ./src/test/resources/application.yml
          echo "${{ secrets.application_test }}" >> ./src/test/resources/application.yml

      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
          context: .

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, artinfo-server-deploy]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker run
        run: |
          #sudo docker rm -f ${{ env.CONTANIER_NAME1 }}
          #sudo docker run -d -p 8080:8080 --name ${{ env.CONTANIER_NAME1 }} --cpus=0.5 --restart always ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}

          #sleep 10
          
          #sudo docker rm -f ${{ env.CONTANIER_NAME2 }}
          sudo docker run -d -p 8081:8080 --name ${{ env.CONTANIER_NAME2 }} --cpus=0.5 --restart always ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
          
          sudo docker image prune -af
